### ISSUE TITLE
auto scanner could be more robust

### ISSUE THREAD

**Issue by derpyjoystick** [n-d-k/OpenCorePkg#12]
Auto scanner seems to stop once it finds the first EFI when scanning the EFI Partition.

My disk structure is as follows:

```
EFI (main NVMe)
--OC
--Windows

EFI (TM Backup)
(Nothing)
```

NDK OC does not detect the Windows boot loader in this scenario.

**Comment by n-d-k** [comment]
Auto scanner was not modified at all. it's the same code in both of this fork and original one.

**Comment by n-d-k** [comment]
If you want anything to show up,  use custom entry.  The whole boot entries menu that feed from Auto scanner can be manipulated via custom entries.

**Comment by derpyjoystick** [comment]
Thanks. Is there any documentation on how to add custom entries?

**Comment by n-d-k** [comment]
All you need is finding the right Device Path which can be lookup from the debug log.
