### ISSUE TITLE
About the OC changing the bios boot sequence

### ISSUE THREAD

**Issue by btwise** [n-d-k/OpenCorePkg#16]
If  enter windows with a boot menu or keyboard shortcut, the next boot will automatically reset the windows boot manage option to the first entry in the bios, something the previous version didn't seem to have?

**Comment by n-d-k** [comment]
nothing was changed to default boot code, like i said everything is the same except icon instead of text.
you have a windows boot manager entry in your bios?

**Comment by M69W** [comment]
same question
<img width="1233" alt="QQ20200204-022404@2x" src="https://user-images.githubusercontent.com/15809201/73679579-a953e180-46f5-11ea-84ee-dd5f27153c8e.png">

**Comment by n-d-k** [comment]
Please read recent changes from OC there was some change they did, not sure if it was the case, But I have no problem with my windows, it's boot normally and there were no Window boot manager in my bios either.   About this fork, i haven't changed anything regarding boot option for awhile.  Keep in mind all the changes from OC official are synced with this fork so make sure you all need to keep an eye on their changes  as well.
