### ISSUE TITLE
Custom entry prevents mounting "Install MacOS" Partition for macOS updates

### ISSUE THREAD

**Issue by Madd33n** [n-d-k/OpenCorePkg#18]
Hi there,

i'm running your fork 0.5.6 with three custom entries. 
1) macOS
2) Win10
3) Carboncopy-Clone

Yesterday I want to update my macOS installation to 10.15.3.
Sadly - the well known "install macOS" partition wasn't shown up in the boot picker after the initial reboot. So no way to update macOS. :( 

After some testing I found out that this seems to be a problem of the custom entries. 
As soon as I deactivate the custom entry of my macOS, the "install macOS"-partition was listed in the boot picker and I was able to make the update. 

But - hopefully - that workaround isn't the planned solution and you'll provide a fix for this.

**Comment by n-d-k** [comment]
the install macOS was actually using the same device path that your custom entry is, and the name was replaced with the custom entry name. If you let it automatically boot to the same macOs that you try to update it would go through the update process just like you pick the install macOS.

**Comment by n-d-k** [comment]
And remember when setting up the custom entry for macOS, always use the one from OC debug log, it's used the blessed device path unlike Clover it's used a static device path.

**Comment by Madd33n** [comment]
Sadly not. Or I misunderstood your information. 
After I didn't saw the expected "install macOS" entry, I choose my custom entry "macOS" -- but it just boots up to the OS without starting the update. 
Maybe there must be a different root path to work correctly?

My current root path is:
PCIRoot-Path of the "preboot" partition - followed by /\UUID_of_the_macOS_partition\System\Library\CoreServices\boot.efi

`PciRoot(0x0)/Pci(0x1D,0x0)/Pci(0x0,0x0)/NVMe(0x1,CA-2D-B4-81-58-38-25-00)/HD(2,GPT,E110BDAF-B514-4D6D-AF72-85604729F566,0x64028,0x3A321FE0)/VenMedia(BE74FCF7-0B7C-49F3-9147-01F4042E6842,AEA9F08706305B4EB5CCBE8E082C5477)/\0E9CC786-3E76-43E0-82C4-37EB4573CF30\System\Library\CoreServices\boot.efi`

**Comment by Madd33n** [comment]
> And remember when setting up the custom entry for macOS, always use the one from OC debug log, it's used the blessed device path unlike Clover it's used a static device path.

Sorry - I don't saw your second reply. Can you tell me how to enable the OC Debug log and how to get the correct information you mentioned?

**Comment by n-d-k** [comment]
Misc->Boot->Debug->Target = 67 and grab the Debug build from edk2\Build\OpenCorePkg\x64\ foler

**Comment by n-d-k** [comment]
the correct device path would listed as last one in the log, as it selected it to boot.

**Comment by Madd33n** [comment]
Ok - I'll will try it and give you a feedback after the next macOS Update. Thanks for your help.

**Comment by n-d-k** [comment]
Worst case scenario, is just disable the custom entry before update, Update won't come very often. So one extra step wouldn't hurt.
