### ISSUE TITLE
ACPI not properly loaded without -v boot-arg

### ISSUE THREAD

**Issue by milouk** [n-d-k/OpenCorePkg#19]
I know it sounds really strange and doesn't make much sense but i tested this many times and it checks out. When NOT having verbose (-v) as a boot-arg, when booting (at the first Apple Logo) my keyboard does NOT light up and i need to unplug and replug it.

However, when enabling verbose in boot-args i can see in the logs that ACPI is properly supplying power to my USBs and the keyboard lights up as it should.

It is a race condition of some sort. Any ideas on how this could be fixed?

** i have been using your fork . Also i can provide my config.plist upon request and any other needed info.

Specs:

* Ryzen 7 2700
* MSI B450 Mortar Max
* RX 460

**Comment by n-d-k** [comment]
It is strange indeed, verbose or non verbose shouldn't affect ACPI.  Sorry, I have no idea how to fix it.
