### ISSUE TITLE
Transparent Icons are not supported in Picker

### ISSUE THREAD

**Issue by SukkaW** [n-d-k/OpenCorePkg#21]
I am trying to port a Clover theme to this forked version of OpenCore. But if I uses `icns` from other Clover themes (which is transparent) will end up in this:

![ScreenShot-2020-03-10-142049](https://user-images.githubusercontent.com/40715044/76326956-538ddd00-6324-11ea-9cb2-143f22d1691d.png)

I have noticed the `icns` files given in the repo all have background. Does that mean the transparent `icns` and images are not supported yet?

**Comment by n-d-k** [comment]
Not all theme will work!..each has its own configuration how it was applied, like selector on top or underneath, and background color to match with icons, there are several images layers need to be used ..etc.  you just have to choose one that works.   Using other theme although was allowed but in the end it was designed with the default theme in mind.
