### ISSUE TITLE
Font issues in menu

### ISSUE THREAD

**Issue by MatthiasStockert** [n-d-k/OpenCorePkg#22]
There are font issues in the menu (see pictures). In my case the issues occur in the names of my custom entries for macOS and Windows.
On my 4K monitor the font and the icons all look very pixelated, but this is not a new issue. It would be nice to have font and icons which look clear on a 4K display anyway.
![ScreenShot-2020-03-11-131826](https://user-images.githubusercontent.com/36683939/76439705-14f83100-63bd-11ea-8bfe-3d3ef7ab6c47.png)
![ScreenShot-2020-03-11-131833](https://user-images.githubusercontent.com/36683939/76439711-19244e80-63bd-11ea-988c-d670d045ca9e.png)

**Comment by n-d-k** [comment]
If everyone is using 4k screen, it will be easy to implemented.  Text pixelated are result of scaling up non-hidpi font type, else you will have a very small text that's impossible to read from distance.

Based on the your screenshot, the font size was adjusted too small in an attempt to correct the text sizing issue , new commit will have a bit bigger size.

The default Icons are 128px scaling up to 256px. Icon will look much better if you can find all 256px Icons to replace them. 

And final thought, this is a boot menu, not an application where you have to spend a long period of time to look at it, eventually, it will be only seen whenever you reboot the system, and how many times does one rebooting system per day?...probably none for normal use.. 

Ps. Latest commit switched to smoother font, which would help with the pixelated on 4k screen.
