### ISSUE TITLE
Can't boot to Linux but success boot to Windows

### ISSUE THREAD

**Issue by oegoeh** [n-d-k/OpenCorePkg#26]
After adding entries to config.plist for windows and Linux, booting to Windows 10 is OK event on Same SSD (my Dell e7270 laptop only have 1 SSD slot)after renaming bootx64.efi to bootx64-OC.efi.
Never success boot to Linux, pickers is show but after pick and grub show, is black screen.
Any clues for boot to Linux?

**Comment by asava** [comment]
This is an [issue with OpenRuntime](https://github.com/acidanthera/bugtracker/issues/491).
It has no relation to this fork.
