### ISSUE TITLE
linux boot error

### ISSUE THREAD

**Issue by Blackiris-no1** [n-d-k/OpenCorePkg#29]
in opencore 0.5.6-0.5.8 Dev version
When booting KaliLinux with open core,
A ramdisk error occurs and a freeze occurs.
And when I mount the Kalin Linux efi partition on my Mac, I get an error that the Kalin Linux EFI boot partition is saved in the BIOS.
Opencore 0.5.5 was able to boot normally, but after updating
This happens.
Is there any other way to boot KaliLinux normally from open core?

**Comment by n-d-k** [comment]
There was many changes from 0.5.5-0.5.8. You may need to read the doc to understand what changed.
