### ISSUE TITLE
OpenShell not show in boot menu

### ISSUE THREAD

**Issue by davidm71** [n-d-k/OpenCorePkg#30]
With recent release of NDK OpenShell.efi not show on boot menu. All other icons and tool items work. Same plist works on standard fork.

**Comment by n-d-k** [comment]
All tools are checked for file existed before it's added to the boot menu, so make sure the file is there in Tools folder and matched the name in config.plist.  

PS. With latest commit, You can now skip the custom/tools entry file checks with Misc->Boot->SkipCustomEntryCheck = YES.

**Comment by davidm71** [comment]
Doesn’t work
