### ISSUE TITLE
OcSimpleBootMenuInternal.h add UI_ICON error

### ISSUE THREAD

**Issue by Blackiris-no1** [n-d-k/OpenCorePkg#31]
In the OcSimpleBootMenuInternal.h file, add a new UI_ICON name to the UI_ICON section
If you build, it will automatically change to version 0.5.9.
In version 0.5.9
The added icon definition does not work properly.
Are there any further modifications?
Or in version 0.5.8
Is there a way to build it?

![ScreenShot-2020-05-08-215533](https://user-images.githubusercontent.com/63716607/81453331-41b1a480-91c4-11ea-8a66-4f4d4149d78f.png)
![스크린샷 2020-05-09 오전 6 51 27](https://user-images.githubusercontent.com/63716607/81453341-45452b80-91c4-11ea-923b-5f395f65b784.png)

**Comment by btwise** [comment]
It has been added here, and you need to add the judging code in OcSimpleBootMenu.c to succeed
