### ISSUE TITLE
AllowNvramReset not shown into OC boot menu

### ISSUE THREAD

**Issue by Ukr55** [n-d-k/OpenCorePkg#5]
Hi n-d-k
Why AllowNvramReset not shown into OC boot menu?
![Screen Shot 2020-01-02 at 15 02 28](https://user-images.githubusercontent.com/18126167/71668259-e6345d80-2d70-11ea-8d7e-6c4d29441974.png)

**Comment by Ukr55** [comment]
maybe you add all changes in documentation?

**Comment by n-d-k** [comment]
Reset Nvram is considered as tool.
- macOS Recovery/Tools Entries are hidden by default, use Spacebar in Boot Menu as a toggle on/off to show/hide these entries.

**Comment by Ukr55** [comment]
ОК Thanks
