### ISSUE TITLE
Using Tools from Boot Picker

### ISSUE THREAD

**Issue by darthsian** [n-d-k/OpenCorePkg#8]
When i use some Tool from Boot Picker (e.g. Shell) so after i quit this tool it won't go back to Boot Picker but i get this error "OC: Tool Tools\<null string> cannot be found! Halting on critical error".

No problem on the original OpenCore.

**Comment by n-d-k** [comment]
Thanks for reporting this, Apparently I don't use any kind of tool :) , so I didn't perform any tool test with the changes I made.  This problem was fixed with latest commit. Appreciate the feedback!
